[package]
name = "rust-fontconfig"
version = "0.1.9"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
edition = "2018"
license = "MIT"
description = "Minimal dependency, pure-Rust alternative to font-loader and servo-fontconfig"
repository = "https://github.com/fschutt/rust-fontconfig"
keywords = ["fontconfig", "font-loader", "font", "system-fonts"]
categories = ["gui"]
readme = "README.md"

[dependencies]
xmlparser = { version = "0.13.3", default-features = false }
mmapio = { version = "0.9.1", default-features = false }
rayon = { version = "1.5.0", default-features = false, optional = true }
allsorts = { version = "0.15.0", default-features = false, features = ["flate2_rust"], optional = true }

[features]
default = ["std", "parsing", "multithreading"]
std = []
multithreading = ["rayon"]
parsing = ["allsorts"]
